language: csharp
solution: contacts-api-dotnet.sln
dotnet: 1.0.1
dist: trusty
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore solution-name.sln
  - dotnet restore
script:
  - dotnet test
